WITH Project_Count AS 
(
    SELECT CLIENT_ID, COUNT(CLIENT_ID) AS PROJECT_NUMBER
    FROM PUBLIC.project
    GROUP BY CLIENT_ID
)

SELECT c.NAME, pc.PROJECT_NUMBER
FROM PUBLIC.client c
JOIN Project_Count pc ON c.ID = pc.CLIENT_ID
WHERE pc.PROJECT_NUMBER = (
    SELECT MAX(PROJECT_NUMBER)
    FROM Project_Count
);