WITH CTE AS (
    SELECT 
        MIN(BIRTHDAY) AS youngest, 
        MAX(BIRTHDAY) AS oldest
    FROM PUBLIC.worker
)
SELECT NAME, BIRTHDAY, 
CASE 
WHEN BIRTHDAY = (SELECT youngest FROM CTE) THEN 'YOUNGEST'
ELSE 'ELDEST'
END AS TYPE
FROM PUBLIC.worker
WHERE BIRTHDAY IN ((SELECT youngest FROM CTE), (SELECT oldest FROM CTE))

