WITH CTE AS(
SELECT DATEDIFF(MONTH, START_DATE, Finish_DATE) AS duration, ID FROM PUBLIC.project
)

SELECT pw.PROJECT_ID, (SUM(w.SALARY)*CTE.duration) AS price  FROM PUBLIC.project_worker AS pW JOIN CTE ON  pW.PROJECT_ID = CTE.ID
JOIN dbo.worker AS w ON pW.WORKER_ID= w.ID
GROUP BY pw.PROJECT_ID, duration
ORDER BY pw.PROJECT_ID ASC